# =============================================================================
# golangci-lint configuration for matlas-cli
# =============================================================================

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - dupl
    - gocognit
    - goconst
    - gocyclo
    - revive
    - prealloc
    - misspell
    - unconvert
    - unparam
    - whitespace
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error