apiVersion: matlas.mongodb.com/v1
kind: ApplyDocument
metadata:
  name: dependencies-and-deletion
resources:
  - apiVersion: matlas.mongodb.com/v1
    kind: Cluster
    metadata:
      name: app-cluster
      deletionPolicy: Retain
    spec:
      projectName: "My Project"
      provider: AWS
      region: us-east-1
      instanceSize: M10

  - apiVersion: matlas.mongodb.com/v1
    kind: DatabaseUser
    metadata:
      name: app-user
      dependsOn: ["app-cluster"]
    spec:
      projectName: "My Project"
      username: app-user
      authDatabase: admin
      password: "${APP_USER_PASSWORD}"
      roles:
        - roleName: readWrite
          databaseName: appdb
      scopes:
        - name: app-cluster
          type: CLUSTER


