# User Password Management Example
# This example demonstrates user creation with the --show-password feature
# Passwords can be displayed during creation and updated afterwards

apiVersion: matlas.mongodb.com/v1
kind: ApplyDocument
metadata:
  name: user-password-management
  labels:
    purpose: example
    feature: password-management
  annotations:
    description: "Example demonstrating user password management and display features"
    passwordDisplay: "supported via --show-password flag"
resources:
  # Service account user with specific database access
  - apiVersion: matlas.mongodb.com/v1
    kind: DatabaseUser
    metadata:
      name: service-account
      labels:
        purpose: service
        type: application
        access-level: readwrite
    spec:
      projectName: "My Project"
      username: service-account
      authDatabase: admin
      password: "${SERVICE_ACCOUNT_PASSWORD}"  # Environment variable for security
      roles:
        - roleName: readWrite
          databaseName: application
        - roleName: read
          databaseName: logs

  # Analytics user with read-only access
  - apiVersion: matlas.mongodb.com/v1
    kind: DatabaseUser
    metadata:
      name: analytics-readonly
      labels:
        purpose: analytics
        type: human
        access-level: readonly
    spec:
      projectName: "My Project"
      username: analytics-readonly
      authDatabase: admin
      password: "${ANALYTICS_PASSWORD}"
      roles:
        - roleName: read
          databaseName: application
        - roleName: read
          databaseName: analytics
        - roleName: read
          databaseName: logs

  # Admin user with elevated privileges
  - apiVersion: matlas.mongodb.com/v1
    kind: DatabaseUser
    metadata:
      name: database-admin
      labels:
        purpose: administration
        type: human
        access-level: admin
    spec:
      projectName: "My Project"
      username: database-admin
      authDatabase: admin
      password: "${DATABASE_ADMIN_PASSWORD}"
      roles:
        - roleName: dbAdminAnyDatabase
          databaseName: admin
        - roleName: readWriteAnyDatabase
          databaseName: admin
        - roleName: userAdminAnyDatabase
          databaseName: admin

  # Scoped user with cluster-specific access
  - apiVersion: matlas.mongodb.com/v1
    kind: DatabaseUser
    metadata:
      name: cluster-specific-user
      labels:
        purpose: application
        scope: cluster-specific
    spec:
      projectName: "My Project"
      username: cluster-specific-user
      authDatabase: admin
      password: "${CLUSTER_USER_PASSWORD}"
      roles:
        - roleName: readWrite
          databaseName: application
      scopes:
        - name: prod-cluster
          type: CLUSTER
