title: "matlas docs"
description: "Unified CLI for MongoDB Atlas and MongoDB"

# Use a maintained docs theme with built-in navigation and search
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Theme settings
search_enabled: true
color_scheme: light

# Navigation order defaults (can be overridden per page)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude non-docs content from the site build
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - _pages/sidebar.md

