# Site settings
title: matlas
description: Unified CLI for MongoDB Atlas and MongoDB databases
url: https://teabranch.github.io
baseurl: /matlas-cli

# Theme settings
theme: just-the-docs

# Color scheme
color_scheme: light

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-seo-tag

# Navigation structure
nav_order: 1

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/teabranch/matlas-cli"

# Makes aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 matlas CLI. Distributed by an <a href=\"https://github.com/teabranch/matlas-cli/tree/main/LICENSE\">MIT license</a>."

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Social links
github_username: teabranch
github_repository: matlas-cli

# Exclude from processing
exclude:
  - vendor/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md

# Include files
include:
  - _pages

  # Add Google Site Verification
webmaster_verifications:
  google: ftuEYbK0wGbauiNVCeBi1PiNo3-lstmDQ7sXyymgu_c
  # You can also add codes for Bing, Yandex, Baidu, and Facebook App ID here 
  # bing: YOUR_BING_CODE
  # yandex: YOUR_YANDEX_CODE
  # baidu: YOUR_BAIDU_CODE
  # facebook_app_id: YOUR_FACEBOOK_APP_ID
  # facebook_admins: YOUR_FACEBOOK_USER_ID
