title: matlas
description: Unified CLI for MongoDB Atlas and MongoDB databases
url: https://teabranch.github.io
baseurl: /matlas-cli

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
color_scheme: light

nav_external_links:
  - title: GitHub
    url: https://github.com/teabranch/matlas-cli

exclude:
  - vendor/
  - node_modules/
  - Gemfile
  - Gemfile.lock