name: Deploy Documentation

on:
  release:
    types: [published]
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: 'latest'
          working-directory: docs

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clean and install dependencies
        working-directory: docs
        run: |
          # Remove old vendor directory and lock file that may have incompatible versions
          rm -rf vendor Gemfile.lock
          # Install latest bundler
          gem install bundler
          # Install dependencies with specific versions for stability
          bundle install --jobs 4 --retry 3

      - name: Build site
        working-directory: docs
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --destination ../_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

